Remove fixed version of google-cloud package (fix logger error in background-update)
There is no specific reason to fix version and to manage this dependency differently (get last version), and it solved the issue below:

for recent image push I have this error with gcloud 0.21.0:

Traceback (most recent call last):
  File "./src/orchestrator/launch_backgroundupdate.py", line 8, in <module>
    init_gcloud_log(GCLOUD_PROJECT, u'background_update', IS_TEST_ENV)
  File "/usr/local/lib/python2.7/site-packages/common/log.py", line 14, in init_gcloud_log
    handler = CloudLoggingHandler(client, logger_name)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/logging/handlers/handlers.py", line 80, in __init__
    self.transport = transport(client, name)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/logging/handlers/transports/background_thread.py", line 154, in __init__
    http = client._connection.credentials.authorize(http)
AttributeError: 'Credentials' object has no attribute 'authorize'

It seems related to change:
https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2726

Upgrade to 0.21.1 fix the issue.