Try to fix new error in travis (missing jre)
ERROR: (gcloud.beta.emulators.datastore.start) To use the Google Cloud Datastore emulator, a Java 7+ JRE must be installed and on your system PATH

following https://github.com/travis-ci/travis-ci/issues/5161