rollback selenium to 2.48 (newest version 2.49 seems to be buggy) (Fix errore i requirement.txt syntax) The error happens in the last travis build and there is a new version of selenium. Reproduced locally.
erro:
self = <test_homepage.NewVisitorTests testMethod=test_save_features>
    def tearDown(self):
>       self.browser.quit()
src/functests/test_homepage.py:12:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
lib/miniconda/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py:74: in quit
    self.service.stop()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <selenium.webdriver.phantomjs.service.Service object at 0x7f29c6910390>
    def stop(self):
        """
            Stops the service.
            """
        if self.log_file != PIPE:
            try:
                self.log_file.close()
            except Exception:
                pass

        if self.process is None:
            return

        self.send_remote_shutdown_command()

        try:
            if self.process:
>               self.process.stdout.close()
E               AttributeError: 'NoneType' object has no attribute 'close'
lib/miniconda/lib/python2.7/site-packages/selenium/webdriver/common/service.py:124: AttributeError